const categories = {
  Healthcare: [
    "Healthcare Infrastructure",
    "Access to Healthcare",
    "Healthcare Policies",
    "Public Health Improvement",
    "Medical Research",
    "Healthcare Services",
    "Patient Care",
    "Health Insurance",
    "Telemedicine",
    "Healthcare Technology",
  ],
  Education: [
    "Educational Facilities",
    "Curriculum Development",
    "Teacher Training",
    "Skill Development",
    "Quality of Education",
    "Early Childhood Education",
    "Higher Education",
    "Vocational Training",
    "Education Technology",
    "Special Education",
  ],
  "Rural Development and Agriculture": [
    "Rural Infrastructure",
    "Agricultural Reforms",
    "Farmer Welfare",
    "Food Security",
    "Rural Economy",
    "Sustainable Farming",
    "Agricultural Technology",
    "Crop Production",
    "Livestock Management",
    "Rural Services",
  ],
  "Infrastructure and Transportation": [
    "Road Development",
    "Bridge Construction",
    "Railway Upgradation",
    "Airport Development",
    "Public Transportation Systems",
    "Urban Planning",
    "Infrastructure Financing",
    "Smart Cities",
    "Traffic Management",
    "Transportation Policy",
  ],
  "Environment and Energy": [
    "Environmental Protection",
    "Climate Change Mitigation",
    "Renewable Energy Sources",
    "Sustainable Energy Practices",
    "Conservation",
    "Pollution Control",
    "Sustainable Development",
    "Energy Policy",
    "Waste Management",
    "Water Management",
  ],
  "Public Safety and Law Enforcement": [
    "Law and Order",
    "Crime Prevention",
    "Police Reforms",
    "Citizen Safety",
    "Emergency Services",
    "Public Safety Policies",
    "Disaster Management",
    "Fire Safety",
    "Traffic Enforcement",
    "Legal Services",
  ],
  "Public Services and Utilities": [
    "Water Supply",
    "Sanitation",
    "Electricity",
    "Waste Management",
    "Public Transport",
    "Telecommunications",
    "Postal Services",
    "Public Libraries",
    "Social Services",
    "Healthcare Services",
  ],
  "Economic Development and Employment": [
    "Economic Growth",
    "Job Opportunities",
    "Business Support",
    "Industry Development",
    "Workforce Development",
    "Unemployment Benefits",
    "Economic Planning",
    "Industrial Development",
    "Tourism",
    "Innovation and Technology",
  ],
  "Social Welfare and Poverty Alleviation": [
    "Social Security",
    "Poverty Reduction",
    "Affordable Housing",
    "Support for Marginalized Communities",
    "Food Assistance",
    "Child Welfare",
    "Elderly Care",
    "Disability Services",
    "Unemployment Insurance",
    "Community Development",
  ],
  "Urban Planning and Housing": [
    "Urban Development",
    "Smart City Projects",
    "Affordable Housing",
    "Urban Sprawl",
    "Slum Rehabilitation",
    "Land Use Planning",
    "Housing Policy",
    "Public Spaces",
    "Transport Planning",
    "Infrastructure Development",
  ],
  "Arts, Culture, and Heritage Preservation": [
    "Promoting Arts",
    "Cultural Activities",
    "Heritage Preservation",
    "Historical Sites",
    "Cultural Heritage",
    "Support for Creative Industries",
    "Museums",
    "Performing Arts",
    "Visual Arts",
    "Literature",
  ],
  "Technology, Innovation, and Digital Infrastructure": [
    "Technological Advancements",
    "Research and Development",
    "Digital Infrastructure",
    "Promoting Innovation",
    "Artificial Intelligence",
    "Cybersecurity",
    "Data Privacy",
    "Digital Literacy",
    "E-Government",
    "Internet Access",
  ],
  "Community Development and Youth Empowerment": [
    "Strengthening Local Communities",
    "Social Cohesion",
    "Youth Empowerment",
    "Skill Development",
    "Entrepreneurship Support",
    "Recreational Activities",
    "Youth Leadership",
    "Community Engagement",
    "Social Entrepreneurship",
    "Youth Employment",
  ],
  "Women's Rights and Gender Equality": [
    "Women's Safety",
    "Economic Empowerment",
    "Representation in Decision-Making",
    "Gender Equality",
    "Women's Health",
    "Gender-Based Violence",
    "Women in Leadership",
    "Gender Equality in Education",
    "Women's Economic Empowerment",
    "Reproductive Rights",
  ],
  "Indigenous Rights and Tribal Affairs": [
    "Indigenous Rights",
    "Welfare of Indigenous Communities",
    "Development of Tribal Communities",
    "Land Rights",
    "Cultural Rights",
    "Indigenous Health",
    "Tribal Governance",
    "Indigenous Education",
    "Tribal Law",
    "Indigenous Languages",
  ],
  "Disability Rights and Accessibility": [
    "Rights of Persons with Disabilities",
    "Inclusion of Persons with Disabilities",
    "Accessibility",
    "Support Services",
    "Accessible Design",
    "Disability Advocacy",
    "Inclusive Education",
    "Disability Legislation",
    "Assistive Technology",
    "Employment Rights",
  ],
  "National Security and Defense": [
    "National Security",
    "Defense Strategies",
    "Border Security",
    "International Cooperation in Security",
    "Military Strategy",
    "Counterterrorism",
    "Cybersecurity",
    "Intelligence Gathering",
    "Defense Policy",
    "Arms Control",
  ],
  "Corruption and Good Governance": [
    "Transparency",
    "Accountability",
    "Good Governance Practices",
    "Combating Corruption",
    "Ethical Governance",
    "Anti-Corruption Measures",
    "Ethics in Government",
    "Public Administration",
    "E-Government",
    "Public Sector Reform",
  ],
  "International Relations and Foreign Policy": [
    "International Relations",
    "Foreign Policy",
    "Trade Agreements",
    "India's Role in Global Affairs",
    "Diplomacy",
    "International Trade",
    "Peacekeeping",
    "Global Governance",
    "Human Rights Policy",
    "International Security",
  ],
  "Sports and Recreation": [
    "Promoting Sports",
    "Recreational Activities",
    "Sports Infrastructure",
    "Support for Athletes",
    "Sports Organizations",
    "Athlete Development",
    "Sports Policy",
    "Recreational Facilities",
    "Sports Medicine",
    "Physical Education",
  ],
  "Child Rights and Protection": [
    "Child Rights",
    "Child Welfare",
    "Child Protection",
    "Child Education",
    "Child Health",
    "Child Safety",
    "Child Abuse Prevention",
    "Child Development",
    "Child Nutrition",
    "Child Legal Rights",
  ],
  "Senior Citizen Welfare": [
    "Senior Healthcare",
    "Social Security",
    "Retirement Benefits",
    "Elderly Care",
    "Senior Services",
    "Elderly Rights",
    "Retirement Planning",
    "Senior Housing",
    "Elderly Nutrition",
    "Senior Community Programs",
  ],
  "Science and Research": [
    "Scientific Research",
    "Innovation",
    "Technological Development",
    "Research Funding",
    "Scientific Discoveries",
    "Research Ethics",
    "Scientific Collaboration",
    "Research and Development",
    "Science Education",
    "Technology Transfer",
  ],
  "Media and Freedom of Expression": [
    "Media Ethics",
    "Press Freedom",
    "Freedom of Expression",
    "Media Regulation",
    "Journalistic Standards",
    "Media Literacy",
    "Digital Media",
    "Media Diversity",
    "Media Transparency",
    "Freedom of Information",
  ],
  "Consumer Protection and Fair Trade Practices": [
    "Consumer Rights",
    "Fair Trade Practices",
    "Business Regulation",
    "Consumer Safety",
    "Product Quality",
    "Consumer Complaints",
    "Consumer Education",
    "Fair Pricing",
    "Business Ethics",
    "Consumer Privacy",
  ],
  "Labor Rights and Welfare": [
    "Labor Rights",
    "Worker Welfare",
    "Workplace Safety",
    "Fair Wages",
    "Employment Rights",
    "Worker Health",
    "Labor Unions",
    "Workplace Discrimination",
    "Worker Training",
    "Labor Legislation",
  ],
  "Disaster Management and Emergency Response": [
    "Disaster Management",
    "Emergency Response",
    "Climate Change Adaptation",
    "Disaster Preparedness",
    "Emergency Services",
    "Disaster Recovery",
    "Crisis Management",
    "Disaster Risk Reduction",
    "Emergency Planning",
    "Disaster Relief",
  ],
};

module.exports = categories;
